title: Startseite

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: blocks
            fieldsets:
              - fullbleed-text
              - verticalnewscardslider
              - logogrid
              - youtube
              - image
            label: Inhalt
            required: true
  sidebar:
    width: 1/3
    sections:
      fieldsRight:
        extends: sections/default-sidebar
      pages:
        type: pages
        label: Unterseiten
        templates:
          - default
          - article
          - horizontalcardlist
          - codeembed
          - soundbox
      files:
        type: files
