title: Site

tabs:
  content:
    label: Content
    icon: text
    sections:
      pages:
        type: pages
        label: Seiten
        templates:
          - article
          - default
          - map
          - horizontalcardlist

  global:
    label: Einstellungen
    icon: list-bullet
    sections:
      menu:
        type: fields
        fields:
          hideToolbar:
            label: Toolbar komplett verbergen?
            type: toggle
            text:
              - "Nein"
              - "Ja"

          toolbar:
            label: Toolbar Elemente
            type: structure
            help: Hier kannst du die Elemente in der Toolbar festlegen, die unterhalb des Hauptmenüs angezeigt wird.
            fields:
              title:
                label: Titel
                type: text
                required: true
              href:
                label: Ziel
                type: pages
                required: true
                multiple: false
                max: 3
              icon:
                label: Icon
                type: select
                options: site.iconOptions
                help: Die Namen der Icons beziehen sich auf das [Carbon Iconset](https://carbondesignsystem.com/elements/icons/library/) von IBM.

          social:
            label: Social Media
            type: structure
            required: false
            fields:
              platform:
                label: Plattform
                type: select
                options:
                  instagram: Instagram
                  twitter: Twitter
                  x: X
                  youtube: YouTube
                  gitlab: GitLab
                  linkedin: LinkedIn
                  mastodon: Mastodon
                  facebook: Facebook
                  xing: Xing
                  github: GitHub
                  website: Website
                  email: E-Mail
                required: true

              target:
                label: URL
                type: url
                required: true

